
data:
  -
    languages:
      - Ruby
      - Perl
      - Python
  -
    websites:
      YAML: yaml.org
      Ruby: ruby-lang.org
      Python: python.org
      Perl:
        - 1
        - 2
        - 3
        - 4